

services:
  # 1. 엘라스틱서치 (검색 엔진 본체)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=movie-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false  # 실습 편의상 보안(ID/PW) 끔
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # 메모리 사용량 제한 (노트북 보호)
    ports:
      - "9200:9200" # 외부 통신 포트
      - "9300:9300"
    networks:
      - movie-net

  # 2. 키바나 (데이터 눈으로 보는 대시보드)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - movie-net

  mysql:
    image: mysql:8.0
    container_name: movie-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: atom
      MYSQL_USER: bts
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    command: # 한글 깨짐 방지
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

networks:
  movie-net:
    driver: bridge